In [1]:
import os
import pandas as pd
import numpy as np
from datetime import datetime as datatime
from pathlib import Path
import torch
import torch.nn as nn
from PIL import Image
import torch.optim as optim
from torchvision import transforms
from torchvision import models
from torch.optim.lr_scheduler import StepLR

from torch.utils.data import Dataset
from torch.utils.data import DataLoader
from torch.utils.tensorboard import SummaryWriter

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,f1_score,precision_score,recall_score,confusion_matrix,classification_report
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.model_selection import train_test_split
from sklearn.utils import resample
from imblearn.over_sampling import SMOTE, ADASYN, RandomOverSampler

from tqdm import tqdm

In [2]:
# import zipfile
# import os

# # 要解压的 zip 文件路径
# train_zip = ('./COMP90086_2024_Project_train.zip')
# test_zip = ('./COMP90086_2024_Project_test.zip')

# # 解压后的目标文件夹（如果不存在则创建）
# train_folder = 'COMP90086_2024_Project_train'
# os.makedirs(train_folder, exist_ok=True)
# test_folder = 'COMP90086_2024_Project_test'
# os.makedirs(test_folder, exist_ok=True)

# # 打开并解压 zip 文件

# with zipfile.ZipFile(train_zip, 'r') as zip_ref:
#     zip_ref.extractall(train_folder)

# with zipfile.ZipFile(test_zip, 'r') as zip_ref:
#     zip_ref.extractall(test_folder)
    
# print(f"Files extracted to {train_folder}")
# print(f"Files extracted to {test_folder}")

In [3]:
csv_path = './input/COMP90086_2024_Project_train/train.csv'
img_dir = './input/COMP90086_2024_Project_train/train'

In [4]:
from src.GoogLeNet_framework import SimpleFineTunedGoogLeNet, ComplexFineTunedGoogLeNet,SingleGoogLeNet
from src.read_data import ReadData, create_model_dir, GetTestDF
from src.eval_module_template import ModelTemplate, EvalTrainDf
from src.train_models import ContinueTrainer, BasicTrainer,BestPrecisionTrainer
from src.tester import GetTestDF, TesterTemplate

In [5]:
if __name__ == "__main__":
    trainer = BasicTrainer(
        csv_path = csv_path,
        img_dir = img_dir, 
        model = SingleGoogLeNet(),
        label_column = 'instability_type',
        store_model_name = 'Singlelayer_For_InstabilityType',
        test_size = 0.2,
        num_epochs = 16, 
        batch_size = 32
    )
    trainer.train()
    

Train dataset size: 6144 Validation dataset size: 1536


Epoch 1/16:   0%|          | 0/192 [00:00<?, ?batch/s]/root/miniconda3/lib/python3.12/site-packages/torch/nn/modules/conv.py:456: UserWarning: Plan failed with a cudnnException: CUDNN_BACKEND_EXECUTION_PLAN_DESCRIPTOR: cudnnFinalize Descriptor Failed cudnn_status: CUDNN_STATUS_NOT_SUPPORTED (Triggered internally at ../aten/src/ATen/native/cudnn/Conv_v8.cpp:919.)
  return F.conv2d(input, weight, bias, self.stride,
Epoch 1/16:   0%|          | 0/192 [00:00<?, ?batch/s]
../aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [0,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [1,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [16,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_fo

RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


In [6]:
if __name__ == "__main__":
    trainer = BasicTrainer(
        csv_path = csv_path,
        img_dir = img_dir, 
        model = SingleGoogLeNet(),
        label_column = 'instability_type',
        store_model_name = 'Epoch32_Singlelayer_For_InstabilityType',
        test_size = 0.2,
        num_epochs = 32, 
        batch_size = 32
    )
    trainer.train()

Train dataset size: 6144 Validation dataset size: 1536


Epoch 1/32: 100%|██████████| 192/192 [00:33<00:00,  5.65batch/s, accuracy=0.667, loss=0.708]  


[0.001]
              precision    recall  f1-score   support

           0       0.58      0.23      0.33       369
           1       0.68      0.91      0.78       777
           2       0.93      0.85      0.89       390

    accuracy                           0.73      1536
   macro avg       0.73      0.66      0.67      1536
weighted avg       0.72      0.73      0.70      1536

[[ 84 272  13]
 [ 56 709  12]
 [  4  56 330]]
Epoch 1/32, Validation Loss: 0.6068, Validation Accuracy: 0.7311
Best model saved! 20241016-1634


Epoch 2/32: 100%|██████████| 192/192 [00:34<00:00,  5.52batch/s, accuracy=0.71, loss=0.631]   


[0.001]
              precision    recall  f1-score   support

           0       0.70      0.06      0.11       369
           1       0.66      0.98      0.79       777
           2       0.97      0.86      0.91       390

    accuracy                           0.73      1536
   macro avg       0.78      0.63      0.60      1536
weighted avg       0.75      0.73      0.66      1536

[[ 21 344   4]
 [  7 765   5]
 [  2  52 336]]
Epoch 2/32, Validation Loss: 0.5814, Validation Accuracy: 0.7305


Epoch 3/32: 100%|██████████| 192/192 [00:35<00:00,  5.47batch/s, accuracy=0.735, loss=0.579]  


[0.001]
              precision    recall  f1-score   support

           0       0.52      0.41      0.46       369
           1       0.76      0.59      0.67       777
           2       0.58      0.96      0.73       390

    accuracy                           0.64      1536
   macro avg       0.62      0.65      0.62      1536
weighted avg       0.66      0.64      0.63      1536

[[150 133  86]
 [136 460 181]
 [  3  13 374]]
Epoch 3/32, Validation Loss: 0.8648, Validation Accuracy: 0.6406


Epoch 4/32: 100%|██████████| 192/192 [00:34<00:00,  5.61batch/s, accuracy=0.743, loss=0.565]  


[0.001]
              precision    recall  f1-score   support

           0       0.63      0.22      0.32       369
           1       0.69      0.94      0.80       777
           2       0.96      0.87      0.92       390

    accuracy                           0.75      1536
   macro avg       0.76      0.68      0.68      1536
weighted avg       0.75      0.75      0.71      1536

[[ 80 281   8]
 [ 42 730   5]
 [  4  46 340]]
Epoch 4/32, Validation Loss: 0.5492, Validation Accuracy: 0.7487
Best model saved! 20241016-1636


Epoch 5/32: 100%|██████████| 192/192 [00:34<00:00,  5.50batch/s, accuracy=0.746, loss=0.554]  


[0.001]
              precision    recall  f1-score   support

           0       0.54      0.43      0.48       369
           1       0.73      0.84      0.78       777
           2       0.98      0.88      0.93       390

    accuracy                           0.75      1536
   macro avg       0.75      0.71      0.73      1536
weighted avg       0.75      0.75      0.74      1536

[[157 207   5]
 [126 649   2]
 [  9  37 344]]
Epoch 5/32, Validation Loss: 0.5442, Validation Accuracy: 0.7487


Epoch 6/32: 100%|██████████| 192/192 [00:35<00:00,  5.48batch/s, accuracy=0.749, loss=0.545]  


[0.001]
              precision    recall  f1-score   support

           0       0.58      0.42      0.48       369
           1       0.74      0.87      0.80       777
           2       0.98      0.88      0.93       390

    accuracy                           0.76      1536
   macro avg       0.76      0.72      0.74      1536
weighted avg       0.76      0.76      0.75      1536

[[154 212   3]
 [ 96 676   5]
 [ 17  30 343]]
Epoch 6/32, Validation Loss: 0.5333, Validation Accuracy: 0.7637
Best model saved! 20241016-1638


Epoch 7/32: 100%|██████████| 192/192 [00:33<00:00,  5.67batch/s, accuracy=0.755, loss=0.537]  


[0.001]
              precision    recall  f1-score   support

           0       0.51      0.58      0.54       369
           1       0.77      0.73      0.75       777
           2       0.94      0.92      0.93       390

    accuracy                           0.74      1536
   macro avg       0.74      0.74      0.74      1536
weighted avg       0.75      0.74      0.75      1536

[[215 146   8]
 [192 570  15]
 [ 13  20 357]]
Epoch 7/32, Validation Loss: 0.5547, Validation Accuracy: 0.7435


Epoch 8/32: 100%|██████████| 192/192 [00:34<00:00,  5.50batch/s, accuracy=0.75, loss=0.533]   


[0.001]
              precision    recall  f1-score   support

           0       0.61      0.37      0.46       369
           1       0.78      0.77      0.77       777
           2       0.69      0.97      0.81       390

    accuracy                           0.72      1536
   macro avg       0.69      0.70      0.68      1536
weighted avg       0.72      0.72      0.71      1536

[[137 160  72]
 [ 84 597  96]
 [  4   9 377]]
Epoch 8/32, Validation Loss: 0.6539, Validation Accuracy: 0.7233


Epoch 9/32: 100%|██████████| 192/192 [00:34<00:00,  5.57batch/s, accuracy=0.759, loss=0.528]  


[0.001]
              precision    recall  f1-score   support

           0       0.59      0.47      0.52       369
           1       0.74      0.85      0.79       777
           2       0.99      0.88      0.93       390

    accuracy                           0.76      1536
   macro avg       0.77      0.73      0.75      1536
weighted avg       0.76      0.76      0.76      1536

[[173 194   2]
 [114 660   3]
 [  8  40 342]]
Epoch 9/32, Validation Loss: 0.5154, Validation Accuracy: 0.7650
Best model saved! 20241016-1640


Epoch 10/32: 100%|██████████| 192/192 [00:33<00:00,  5.71batch/s, accuracy=0.769, loss=0.503]  


[0.001]
              precision    recall  f1-score   support

           0       0.51      0.56      0.53       369
           1       0.77      0.74      0.76       777
           2       0.95      0.94      0.94       390

    accuracy                           0.75      1536
   macro avg       0.74      0.74      0.74      1536
weighted avg       0.75      0.75      0.75      1536

[[205 157   7]
 [189 576  12]
 [ 11  14 365]]
Epoch 10/32, Validation Loss: 0.5497, Validation Accuracy: 0.7461


Epoch 11/32: 100%|██████████| 192/192 [00:34<00:00,  5.51batch/s, accuracy=0.764, loss=0.528]  


[0.001]
              precision    recall  f1-score   support

           0       0.58      0.34      0.43       369
           1       0.69      0.89      0.78       777
           2       0.98      0.79      0.87       390

    accuracy                           0.73      1536
   macro avg       0.75      0.67      0.69      1536
weighted avg       0.74      0.73      0.72      1536

[[126 239   4]
 [ 81 693   3]
 [ 11  71 308]]
Epoch 11/32, Validation Loss: 0.6066, Validation Accuracy: 0.7337


Epoch 12/32: 100%|██████████| 192/192 [00:34<00:00,  5.62batch/s, accuracy=0.766, loss=0.517]  


[0.001]
              precision    recall  f1-score   support

           0       0.54      0.62      0.58       369
           1       0.78      0.74      0.76       777
           2       0.95      0.91      0.93       390

    accuracy                           0.75      1536
   macro avg       0.76      0.76      0.75      1536
weighted avg       0.77      0.75      0.76      1536

[[229 134   6]
 [186 577  14]
 [ 12  25 353]]
Epoch 12/32, Validation Loss: 0.5451, Validation Accuracy: 0.7546


Epoch 13/32: 100%|██████████| 192/192 [00:33<00:00,  5.67batch/s, accuracy=0.77, loss=0.522]   


[0.001]
              precision    recall  f1-score   support

           0       0.78      0.17      0.28       369
           1       0.69      0.97      0.81       777
           2       0.98      0.90      0.94       390

    accuracy                           0.76      1536
   macro avg       0.82      0.68      0.68      1536
weighted avg       0.78      0.76      0.71      1536

[[ 64 302   3]
 [ 16 756   5]
 [  2  38 350]]
Epoch 13/32, Validation Loss: 0.5512, Validation Accuracy: 0.7617


Epoch 14/32: 100%|██████████| 192/192 [00:34<00:00,  5.62batch/s, accuracy=0.769, loss=0.506]  


[0.001]
              precision    recall  f1-score   support

           0       0.62      0.47      0.54       369
           1       0.76      0.87      0.81       777
           2       0.97      0.91      0.94       390

    accuracy                           0.78      1536
   macro avg       0.78      0.75      0.76      1536
weighted avg       0.78      0.78      0.78      1536

[[173 189   7]
 [ 99 673   5]
 [  5  29 356]]
Epoch 14/32, Validation Loss: 0.4934, Validation Accuracy: 0.7826
Best model saved! 20241016-1643


Epoch 15/32: 100%|██████████| 192/192 [00:34<00:00,  5.51batch/s, accuracy=0.774, loss=0.502]  


[0.0001]
              precision    recall  f1-score   support

           0       0.63      0.35      0.45       369
           1       0.73      0.87      0.79       777
           2       0.89      0.93      0.91       390

    accuracy                           0.76      1536
   macro avg       0.75      0.71      0.72      1536
weighted avg       0.75      0.76      0.74      1536

[[128 232   9]
 [ 68 675  34]
 [  7  21 362]]
Epoch 15/32, Validation Loss: 0.5410, Validation Accuracy: 0.7585


Epoch 16/32: 100%|██████████| 192/192 [00:33<00:00,  5.65batch/s, accuracy=0.79, loss=0.465]   


[0.0001]
              precision    recall  f1-score   support

           0       0.62      0.48      0.54       369
           1       0.76      0.87      0.81       777
           2       0.99      0.91      0.95       390

    accuracy                           0.78      1536
   macro avg       0.79      0.75      0.76      1536
weighted avg       0.78      0.78      0.78      1536

[[176 192   1]
 [100 674   3]
 [ 10  26 354]]
Epoch 16/32, Validation Loss: 0.4752, Validation Accuracy: 0.7839
Best model saved! 20241016-1645


Epoch 17/32: 100%|██████████| 192/192 [00:34<00:00,  5.63batch/s, accuracy=0.797, loss=0.444]  


[0.0001]
              precision    recall  f1-score   support

           0       0.68      0.39      0.50       369
           1       0.74      0.91      0.82       777
           2       0.97      0.93      0.95       390

    accuracy                           0.79      1536
   macro avg       0.80      0.74      0.76      1536
weighted avg       0.79      0.79      0.77      1536

[[145 219   5]
 [ 63 707   7]
 [  5  23 362]]
Epoch 17/32, Validation Loss: 0.4777, Validation Accuracy: 0.7904
Best model saved! 20241016-1645


Epoch 18/32: 100%|██████████| 192/192 [00:34<00:00,  5.50batch/s, accuracy=0.807, loss=0.435]  


[0.0001]
              precision    recall  f1-score   support

           0       0.68      0.42      0.52       369
           1       0.76      0.90      0.82       777
           2       0.96      0.93      0.94       390

    accuracy                           0.79      1536
   macro avg       0.80      0.75      0.76      1536
weighted avg       0.79      0.79      0.78      1536

[[156 206   7]
 [ 69 698  10]
 [  6  20 364]]
Epoch 18/32, Validation Loss: 0.4661, Validation Accuracy: 0.7930
Best model saved! 20241016-1646


Epoch 19/32: 100%|██████████| 192/192 [00:34<00:00,  5.59batch/s, accuracy=0.813, loss=0.425]  


[0.0001]
              precision    recall  f1-score   support

           0       0.63      0.49      0.55       369
           1       0.77      0.87      0.82       777
           2       0.98      0.93      0.96       390

    accuracy                           0.80      1536
   macro avg       0.80      0.77      0.78      1536
weighted avg       0.79      0.80      0.79      1536

[[181 185   3]
 [ 96 678   3]
 [  9  17 364]]
Epoch 19/32, Validation Loss: 0.4633, Validation Accuracy: 0.7962
Best model saved! 20241016-1647


Epoch 20/32: 100%|██████████| 192/192 [00:34<00:00,  5.51batch/s, accuracy=0.81, loss=0.42]    


[0.0001]
              precision    recall  f1-score   support

           0       0.67      0.41      0.51       369
           1       0.75      0.91      0.82       777
           2       0.99      0.93      0.96       390

    accuracy                           0.80      1536
   macro avg       0.80      0.75      0.76      1536
weighted avg       0.79      0.80      0.78      1536

[[152 216   1]
 [ 66 709   2]
 [  8  21 361]]
Epoch 20/32, Validation Loss: 0.4661, Validation Accuracy: 0.7956


Epoch 21/32: 100%|██████████| 192/192 [00:35<00:00,  5.43batch/s, accuracy=0.817, loss=0.411] 


[0.0001]
              precision    recall  f1-score   support

           0       0.65      0.43      0.52       369
           1       0.76      0.89      0.82       777
           2       0.96      0.93      0.94       390

    accuracy                           0.79      1536
   macro avg       0.79      0.75      0.76      1536
weighted avg       0.78      0.79      0.78      1536

[[159 202   8]
 [ 80 688   9]
 [  7  19 364]]
Epoch 21/32, Validation Loss: 0.4671, Validation Accuracy: 0.7884


Epoch 22/32: 100%|██████████| 192/192 [00:33<00:00,  5.67batch/s, accuracy=0.822, loss=0.401]  


[0.0001]
              precision    recall  f1-score   support

           0       0.61      0.52      0.56       369
           1       0.78      0.84      0.81       777
           2       0.96      0.94      0.95       390

    accuracy                           0.79      1536
   macro avg       0.78      0.77      0.77      1536
weighted avg       0.78      0.79      0.78      1536

[[191 172   6]
 [114 654   9]
 [  7  17 366]]
Epoch 22/32, Validation Loss: 0.4584, Validation Accuracy: 0.7884


Epoch 23/32: 100%|██████████| 192/192 [00:35<00:00,  5.47batch/s, accuracy=0.82, loss=0.401]   


[0.0001]
              precision    recall  f1-score   support

           0       0.64      0.49      0.55       369
           1       0.77      0.87      0.82       777
           2       0.98      0.94      0.96       390

    accuracy                           0.80      1536
   macro avg       0.80      0.77      0.78      1536
weighted avg       0.79      0.80      0.79      1536

[[180 185   4]
 [ 94 679   4]
 [  9  14 367]]
Epoch 23/32, Validation Loss: 0.4526, Validation Accuracy: 0.7982
Best model saved! 20241016-1650


Epoch 24/32: 100%|██████████| 192/192 [00:35<00:00,  5.48batch/s, accuracy=0.818, loss=0.396]  


[0.0001]
              precision    recall  f1-score   support

           0       0.69      0.44      0.53       369
           1       0.76      0.90      0.82       777
           2       0.97      0.93      0.95       390

    accuracy                           0.80      1536
   macro avg       0.80      0.76      0.77      1536
weighted avg       0.79      0.80      0.78      1536

[[161 204   4]
 [ 66 702   9]
 [  6  23 361]]
Epoch 24/32, Validation Loss: 0.4633, Validation Accuracy: 0.7969


Epoch 25/32: 100%|██████████| 192/192 [00:34<00:00,  5.63batch/s, accuracy=0.822, loss=0.389]  


[0.0001]
              precision    recall  f1-score   support

           0       0.62      0.52      0.57       369
           1       0.78      0.86      0.82       777
           2       0.98      0.93      0.96       390

    accuracy                           0.79      1536
   macro avg       0.79      0.77      0.78      1536
weighted avg       0.79      0.79      0.79      1536

[[192 174   3]
 [107 666   4]
 [ 10  17 363]]
Epoch 25/32, Validation Loss: 0.4639, Validation Accuracy: 0.7949


Epoch 26/32: 100%|██████████| 192/192 [00:34<00:00,  5.50batch/s, accuracy=0.82, loss=0.389]   


[0.0001]
              precision    recall  f1-score   support

           0       0.68      0.45      0.54       369
           1       0.76      0.89      0.82       777
           2       0.96      0.94      0.95       390

    accuracy                           0.80      1536
   macro avg       0.80      0.76      0.77      1536
weighted avg       0.79      0.80      0.79      1536

[[165 201   3]
 [ 74 692  11]
 [  4  18 368]]
Epoch 26/32, Validation Loss: 0.4645, Validation Accuracy: 0.7975


Epoch 27/32: 100%|██████████| 192/192 [00:34<00:00,  5.54batch/s, accuracy=0.826, loss=0.385]  


[0.0001]
              precision    recall  f1-score   support

           0       0.69      0.45      0.55       369
           1       0.76      0.89      0.82       777
           2       0.96      0.94      0.95       390

    accuracy                           0.80      1536
   macro avg       0.80      0.76      0.77      1536
weighted avg       0.79      0.80      0.79      1536

[[167 196   6]
 [ 71 695  11]
 [  5  18 367]]
Epoch 27/32, Validation Loss: 0.4637, Validation Accuracy: 0.8001
Best model saved! 20241016-1652


Epoch 28/32: 100%|██████████| 192/192 [00:34<00:00,  5.63batch/s, accuracy=0.84, loss=0.369]   


[0.0001]
              precision    recall  f1-score   support

           0       0.70      0.43      0.53       369
           1       0.76      0.90      0.82       777
           2       0.97      0.95      0.96       390

    accuracy                           0.80      1536
   macro avg       0.81      0.76      0.77      1536
weighted avg       0.80      0.80      0.79      1536

[[158 206   5]
 [ 68 701   8]
 [  1  19 370]]
Epoch 28/32, Validation Loss: 0.4638, Validation Accuracy: 0.8001


Epoch 29/32: 100%|██████████| 192/192 [00:35<00:00,  5.48batch/s, accuracy=0.833, loss=0.374]  


[0.0001]
              precision    recall  f1-score   support

           0       0.63      0.49      0.55       369
           1       0.76      0.86      0.81       777
           2       0.97      0.93      0.95       390

    accuracy                           0.79      1536
   macro avg       0.79      0.76      0.77      1536
weighted avg       0.78      0.79      0.78      1536

[[181 184   4]
 [102 669   6]
 [  6  22 362]]
Epoch 29/32, Validation Loss: 0.4665, Validation Accuracy: 0.7891


Epoch 30/32: 100%|██████████| 192/192 [00:34<00:00,  5.57batch/s, accuracy=0.833, loss=0.376]  


[1e-05]
              precision    recall  f1-score   support

           0       0.67      0.51      0.58       369
           1       0.78      0.87      0.83       777
           2       0.96      0.95      0.96       390

    accuracy                           0.81      1536
   macro avg       0.80      0.78      0.79      1536
weighted avg       0.80      0.81      0.80      1536

[[189 174   6]
 [ 90 679   8]
 [  5  14 371]]
Epoch 30/32, Validation Loss: 0.4628, Validation Accuracy: 0.8066
Best model saved! 20241016-1654


Epoch 31/32: 100%|██████████| 192/192 [00:33<00:00,  5.70batch/s, accuracy=0.847, loss=0.353]  


[1e-05]
              precision    recall  f1-score   support

           0       0.66      0.48      0.56       369
           1       0.77      0.87      0.82       777
           2       0.96      0.94      0.95       390

    accuracy                           0.80      1536
   macro avg       0.80      0.76      0.77      1536
weighted avg       0.79      0.80      0.79      1536

[[178 187   4]
 [ 87 679  11]
 [  3  21 366]]
Epoch 31/32, Validation Loss: 0.4715, Validation Accuracy: 0.7962


Epoch 32/32: 100%|██████████| 192/192 [00:34<00:00,  5.51batch/s, accuracy=0.845, loss=0.347]  


[1e-05]
              precision    recall  f1-score   support

           0       0.66      0.49      0.56       369
           1       0.77      0.88      0.82       777
           2       0.97      0.95      0.96       390

    accuracy                           0.80      1536
   macro avg       0.80      0.77      0.78      1536
weighted avg       0.80      0.80      0.79      1536

[[180 186   3]
 [ 86 682   9]
 [  5  14 371]]
Epoch 32/32, Validation Loss: 0.4624, Validation Accuracy: 0.8027
Finished Training
Best validation accuracy: 0.8066


# Get trainer predicted probabilities

In [5]:
trainer_instabType = EvalTrainDf(
    model_path = './models/_Epoch32_Singlelayer_For_InstabilityType_1/best_model.pth',
    model= SingleGoogLeNet(),
    label_column = 'instability_type',
    csv_path = csv_path, 
    img_dir= img_dir, 
    test_size=0.2,
    batch_size=32
    )
trainer_instabType.validate()

Train dataset size: 6144 Validation dataset size: 1536


/root/miniconda3/lib/python3.12/site-packages/torch/nn/modules/conv.py:456: UserWarning: Plan failed with a cudnnException: CUDNN_BACKEND_EXECUTION_PLAN_DESCRIPTOR: cudnnFinalize Descriptor Failed cudnn_status: CUDNN_STATUS_NOT_SUPPORTED (Triggered internally at ../aten/src/ATen/native/cudnn/Conv_v8.cpp:919.)
  return F.conv2d(input, weight, bias, self.stride,


In [6]:
pred_labels = trainer_instabType.pred_labels
# pred_labels = [pred+1 for pred in pred_labels]
pred_outputs = trainer_instabType.pred_outputs
gt_labels = trainer_instabType.gt_labels
gt_labels = [gt-1 for gt in gt_labels]

In [7]:
train_instab_preds = pd.DataFrame(pred_outputs, columns = ['class_1', 'class_2','class_3'])
# train_instab_preds['pred_class'] = [pred+1 for pred in pred_labels]
# train_instab_preds['true_class'] = gt_labels

In [8]:
train_instab_preds.head()

class_1   class_2   class_3
0  1.555159  0.683043 -4.767675
1 -4.594847 -4.360948  6.287295
2 -0.116200  2.315863 -4.940237
3 -0.163955  2.248013 -4.829304
4  2.305248  0.173829 -5.400097

In [9]:
accuracy_score(gt_labels, pred_labels)

0.051432291666666664

In [5]:
valid_instabType = ModelTemplate(
    model_path = './models/_Epoch32_Singlelayer_For_InstabilityType_1/best_model.pth',
    model= SingleGoogLeNet(),
    label_column = 'instability_type',
    csv_path = csv_path, 
    img_dir= img_dir, 
    test_size=0.2,
    batch_size=32
    )
valid_instabType.validate()

Train dataset size: 6144 Validation dataset size: 1536


/root/miniconda3/lib/python3.12/site-packages/torch/nn/modules/conv.py:456: UserWarning: Plan failed with a cudnnException: CUDNN_BACKEND_EXECUTION_PLAN_DESCRIPTOR: cudnnFinalize Descriptor Failed cudnn_status: CUDNN_STATUS_NOT_SUPPORTED (Triggered internally at ../aten/src/ATen/native/cudnn/Conv_v8.cpp:919.)
  return F.conv2d(input, weight, bias, self.stride,


              precision    recall  f1-score   support

          -1       0.00      0.00      0.00       369
           0       0.00      0.00      0.00       777
           1       0.01      0.01      0.01       390
           2       0.00      0.00      0.00         0
           3       0.00      0.00      0.00         0

    accuracy                           0.00      1536
   macro avg       0.00      0.00      0.00      1536
weighted avg       0.00      0.00      0.00      1536

[[  0   0 194 173   2]
 [  0   0  85 683   9]
 [  0   0   3  14 373]
 [  0   0   0   0   0]
 [  0   0   0   0   0]]


0.001953125

In [6]:
valid_pred_labels = valid_instabType.pred_labels
valid_pred_outputs = valid_instabType.pred_outputs
valid_gt_labels = valid_instabType.gt_labels

In [7]:
accuracy_score(valid_gt_labels, valid_pred_labels)

0.001953125

# Load model of predicting stable height

In [16]:
valider_stabHei = ModelTemplate(
    model_path = './models/20241012-StableHeight-BestModel-net8-acc0666/best_model.pth',
    model= ComplexFineTunedGoogLeNet(),
    label_column = 'stable_height',
    csv_path = csv_path, img_dir= img_dir, 
    test_size=0.2,
    batch_size=32
    )
valider_stabHei.validate()

Train dataset size: 6144 Validation dataset size: 1536
              precision    recall  f1-score   support

           0       0.73      0.73      0.73       384
           1       0.72      0.71      0.72       384
           2       0.62      0.70      0.65       307
           3       0.57      0.63      0.60       230
           4       0.61      0.51      0.55       154
           5       0.60      0.31      0.41        77

    accuracy                           0.66      1536
   macro avg       0.64      0.60      0.61      1536
weighted avg       0.66      0.66      0.66      1536

[[281  35  29  28  10   1]
 [ 39 274  35  22  10   4]
 [ 25  44 214  17   3   4]
 [ 19  13  38 146  12   2]
 [  7   8  16  40  78   5]
 [ 12   8  15   3  15  24]]


0.662109375

# Load model of predicting total height

In [39]:
valider_tt_height = ModelTemplate(
    model_path = './models/20241014-TotalHeight-Classification-net8/best_model.pth',
    model=ComplexFineTunedGoogLeNet(),
    label_column = 'total_height',
    csv_path = csv_path, img_dir= img_dir, 
    test_size=0.2,
    batch_size=32
    )
valider_tt_height.validate()

Train dataset size: 6144 Validation dataset size: 1536
              precision    recall  f1-score   support

           1       0.95      1.00      0.97       149
           2       0.93      0.96      0.94       222
           3       0.91      0.95      0.93       304
           4       0.93      0.91      0.92       395
           5       0.98      0.94      0.96       466

    accuracy                           0.94      1536
   macro avg       0.94      0.95      0.94      1536
weighted avg       0.94      0.94      0.94      1536

[[149   0   0   0   0]
 [  8 213   1   0   0]
 [  0  16 288   0   0]
 [  0   1  25 360   9]
 [  0   0   1  29 436]]


0.94140625

# Combine three models

In [40]:
instab_predictions = valid_instabType.pred_labels
tt_predictions = valider_tt_height.pred_labels
stable_hei_predictions = valider_stabHei.pred_labels

In [41]:
print(set(instab_predictions)), print(set(tt_predictions)), print(set(stable_hei_predictions))

{0, 1, 2}
{1, 2, 3, 4, 5}
{0, 1, 2, 3, 4, 5}


(None, None, None)

In [15]:
gt_stable_hei = valider_stabHei.val_data.stable_height.tolist()

In [16]:
combined_predictions = []
for idx in range(len(instab_predictions)):
    if instab_predictions[idx] == 0:
        combined_predictions.append(tt_predictions[idx])
    else:
        combined_predictions.append(stable_hei_predictions[idx])

In [18]:
accuracy_score(gt_stable_hei, combined_predictions)

0.07877604166666667

# Test Prediction

In [4]:
stabHei_predictor = TesterTemplate(
    model_path = './models/20241012-StableHeight-BestModel-net8-acc0666/best_model.pth',
    model= ComplexFineTunedGoogLeNet(),
    label_column = 'stable_height',
    csv_path= './input/COMP90086_2024_Project_train/train.csv',
    img_dir= './input/COMP90086_2024_Project_train/train',
    batch_size=32
    )
stablehei_pred,img_ids = stabHei_predictor.predict()

testing:   0%|          | 0/240 [00:00<?, ?it/s]/root/miniconda3/lib/python3.12/site-packages/torch/nn/modules/conv.py:456: UserWarning: Plan failed with a cudnnException: CUDNN_BACKEND_EXECUTION_PLAN_DESCRIPTOR: cudnnFinalize Descriptor Failed cudnn_status: CUDNN_STATUS_NOT_SUPPORTED (Triggered internally at ../aten/src/ATen/native/cudnn/Conv_v8.cpp:919.)
  return F.conv2d(input, weight, bias, self.stride,
testing: 100%|██████████| 240/240 [00:09<00:00, 24.92it/s]


In [5]:
train_df = pd.read_csv('./input/COMP90086_2024_Project_train/train.csv')

In [6]:
accuracy_score(train_df['stable_height'], stablehei_pred)

0.7033854166666667

In [20]:
tt_height_predictor = TesterTemplate(
    model=ComplexFineTunedGoogLeNet(),
    model_path='./models/20241014-TotalHeight-Classification-net8/best_model.pth',
    csv_path= './input/COMP90086_2024_Project_train/train.csv',
    img_dir= './input/COMP90086_2024_Project_train/train',
    label_column = 'total_height',
    batch_size=32  
)
# Use the predictor to generate predictions
tt_test_pred,img_ids  = tt_height_predictor.predict()
accuracy_score(train_df['total_height'], tt_test_pred)

testing: 100%|██████████| 240/240 [00:09<00:00, 25.07it/s]


0.17877604166666666

In [21]:
instabType_predictor = TesterTemplate(
    model_path = './models/_Epoch32_Singlelayer_For_InstabilityType_1/best_model.pth',
    model= SingleGoogLeNet(),
    csv_path= './input/COMP90086_2024_Project_train/train.csv',
    img_dir= './input/COMP90086_2024_Project_train/train',
    label_column = 'instability_type',
    batch_size=32
    )
instable_pred,img_ids  = instabType_predictor.predict()
accuracy_score(train_df['instability_type'], instable_pred)

testing: 100%|██████████| 240/240 [00:09<00:00, 24.10it/s]


0.373828125

In [5]:
stabHei_predictor = TesterTemplate(
    model_path = './models/20241012-StableHeight-BestModel-net8-acc0666/best_model.pth',
    model= ComplexFineTunedGoogLeNet(),
    label_column = 'stable_height',
    csv_path= './input/COMP90086_2024_Project_test/test.csv',
    img_dir= './input/COMP90086_2024_Project_test/test',
    batch_size=32
    )
stablehei_pred = stabHei_predictor.predict()

testing:   0%|          | 0/60 [00:00<?, ?it/s]/root/miniconda3/lib/python3.12/site-packages/torch/nn/modules/conv.py:456: UserWarning: Plan failed with a cudnnException: CUDNN_BACKEND_EXECUTION_PLAN_DESCRIPTOR: cudnnFinalize Descriptor Failed cudnn_status: CUDNN_STATUS_NOT_SUPPORTED (Triggered internally at ../aten/src/ATen/native/cudnn/Conv_v8.cpp:919.)
  return F.conv2d(input, weight, bias, self.stride,
testing: 100%|██████████| 60/60 [00:02<00:00, 21.97it/s]


In [6]:
tt_height_predictor = TesterTemplate(
    model=ComplexFineTunedGoogLeNet(),
    model_path='./models/20241014-TotalHeight-Classification-net8/best_model.pth',
    csv_path= './input/COMP90086_2024_Project_test/test.csv',
    img_dir= './input/COMP90086_2024_Project_test/test',
    label_column = 'total_height',
    batch_size=32  
)
# Use the predictor to generate predictions
tt_test_pred = tt_height_predictor.predict()

testing: 100%|██████████| 60/60 [00:02<00:00, 25.80it/s]


In [7]:
instabType_predictor = TesterTemplate(
    model_path = './models/_Epoch32_Singlelayer_For_InstabilityType_1/best_model.pth',
    model= SingleGoogLeNet(),
    csv_path= './input/COMP90086_2024_Project_test/test.csv',
    img_dir= './input/COMP90086_2024_Project_test/test',
    label_column = 'instability_type',
    batch_size=32
    )
instable_pred = instabType_predictor.predict()

testing: 100%|██████████| 60/60 [00:02<00:00, 25.06it/s]


In [8]:
len(instable_pred), len(tt_test_pred), len(stablehei_pred)

(1920, 1920, 1920)

In [9]:
print(set(instable_pred))

{1, 2, 3}


In [10]:
print(set(tt_test_pred))

{2, 3, 4, 5, 6}


In [11]:
print(set(stablehei_pred))

{1, 2, 3, 4, 5, 6}


In [12]:
combined_test = []
for idx in range(len(instable_pred)):
    if instable_pred[idx] == 1:
        combined_test.append(tt_test_pred[idx])
    else:
        combined_test.append(stablehei_pred[idx])

In [13]:
test_df = pd.read_csv('./input/COMP90086_2024_Project_test/test.csv')
test_df.head()

id
0    95
1   706
2  2854
3  3093
4  4283

In [14]:
test_df['stable_height'] = combined_test
test_df.reset_index(drop=True)
test_df.head()

id  stable_height
0    95              5
1   706              2
2  2854              1
3  3093              3
4  4283              2

In [15]:
test_df.to_csv('twostepprediction.csv', index=False)